# Problem 1

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np 

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
print("Soru2")
m = np.random.randint(0,10,size = 5)
print(m)

# 3 - matris'in boyutunu öğrenin
print("Soru3")
print(m.ndim)

# 4 - matris'i yeniden boyutlandırın
print("Soru4")
m2= m.reshape(5,1)
print(m2)


# 5 - matris'in boyut sayısını öğrenin
print("Soru5")
m.shape
print(m.shape)


Soru2
[3 1 4 8 3]
Soru3
1
Soru4
[[3]
 [1]
 [4]
 [8]
 [3]]
Soru5
(5,)


# Problem 2

In [5]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
print("Soru1")
m = np.array([i for i in range(11) if i % 2 !=0])
print(m)

# 2 - Oluşturduğunuz matrisi parçalayın
print("Soru2")
val1, val2 = np.array_split(m,2) #2 parçaya ayırmak için
print(val1)
print(val2)

# 3 - Parçalanmış matrisleri birleştirin
print("Soru3")
birlesmis = np.concatenate((val1,val2))
print(birlesmis)



Soru1
[1 3 5 7 9]
Soru2
[1 3 5]
[7 9]
Soru3
[1 3 5 7 9]


# Problem 3

In [15]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
print("Soru1")
sayi = np.arange(5,100,2)
matrix = np.random.choice(sayi, size=10)
print(matrix)

# 2 - matris'in özelliklerini inceleyin
print("Soru2")
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)


Soru1
[27 87 19 69 49 37 73 31 97 41]
Soru2
(10,)
1
10
