# Problem 1 

In [3]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
print("Soru2")
dizi = np.array([1,3,5,4,2])
print(dizi)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print("Soru3")
print(np.sort(dizi))



Soru2
[1 3 5 4 2]
Soru3
[1 2 3 4 5]


# Problem 2

In [12]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
print("Soru1")
dizi1 = np.array([10,15,30,45,60])
print(dizi1)


# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
print("Soru2")
dizi2 = np.arange(5,16)
print(dizi2)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
print("Soru3")
dizi3= np.arange(50,101,5)
print(dizi3)


# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
print("Soru4")
dizi4= np.zeros(10)
print(dizi4)


# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
print("Soru5")
dizi5 = np.ones(5)
print(dizi5)


# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
print("Soru6")
dizi6 = np.linspace(0,100,5)
print(dizi6)


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
print("Soru7")
dizi7 = np.random.randint(10,31, size=5)
print(dizi7)


# 8- [-1 ile 1] arasında 10 adet sayı üretin.
print("Soru8")
dizi8 = np.linspace(-1,1,10)                # eşit aralıklarda lindspace kullanıyoruz
print(dizi8)


# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
print("Soru9")
dizi9 = np.random.randint(10,51, size=(3,5))
print(dizi9)


# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print("Soru10")
row_sum = dizi9.sum(axis=1)
columns_sum = dizi9.sum(axis=0)
print("Row_sum:", row_sum)
print("Columns_sum:", columns_sum)


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print("Soru11")
buyuk = dizi9.max()
en_kucuk = dizi9.min()
average = dizi9.mean()
print("En büyük:", buyuk)
print("En küçük:", en_kucuk)
print("Ortalama:", average)


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print("Soru12")
maximum_index = np.unravel_index(dizi9.argmax(), dizi9.shape)
print(maximum_index)


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
print("Soru13")
dizi13 = np.arange(10,21)
ilk_uç = dizi13[0:3]
print(ilk_uç)


# 14- Üretilen dizinin elemanlarını tersten yazdırın.print("Soru2")
print("Soru14")
ters = dizi13[::-1]
print(ters)


# 15- Üretilen matrisin ilk satırını seçiniz.
print("Soru15")
ilk_satir = dizi13[0]
print(ilk_satir)


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print("Soru16")
value = dizi9[1,2]
print(value)



# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print("Soru17")
ilk_elemanlar = dizi9[:,0]
print(dizi13)
print( ilk_elemanlar)



# 18- Üretilen matrisin her bir elemanının karesini alınız.
print("Soru18")
squart = dizi13**2
print(dizi13)
print(squart)


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
print("Soru19")
dizi19 = np.random.randint(-50,51, size =(3,5))
print(dizi19)

pozitif_cift = dizi19[(dizi19 > 0) & (dizi19 %2==0)]
print(pozitif_cift)


Soru1
[10 15 30 45 60]
Soru2
[ 5  6  7  8  9 10 11 12 13 14 15]
Soru3
[ 50  55  60  65  70  75  80  85  90  95 100]
Soru4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Soru5
[1. 1. 1. 1. 1.]
Soru6
[  0.  25.  50.  75. 100.]
Soru7
[11 16 28 30 16]
Soru8
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
Soru9
[[10 24 36 50 41]
 [18 42 44 45 48]
 [37 25 12 39 36]]
Soru10
Row_sum: [161 197 149]
Columns_sum: [ 65  91  92 134 125]
Soru11
En büyük: 50
En küçük: 10
Ortalama: 33.8
Soru12
(np.int64(0), np.int64(3))
Soru13
[10 11 12]
Soru14
[20 19 18 17 16 15 14 13 12 11 10]
Soru15
10
Soru16
44
Soru17
[10 11 12 13 14 15 16 17 18 19 20]
[10 18 37]
Soru18
[10 11 12 13 14 15 16 17 18 19 20]
[100 121 144 169 196 225 256 289 324 361 400]
Soru19
[[-35 -32  26  48  -8]
 [ 26  27  38  14  29]
 [  6  31 -42  28  20]]
[26 48 26 38 14  6 28 20]


In [13]:
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print("Soru16")
value = dizi9[1,2]
print(value)



# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print("Soru17")
ilk_elemanlar = dizi9[:,0]
print(dizi13)
print( ilk_elemanlar)



# 18- Üretilen matrisin her bir elemanının karesini alınız.
print("Soru18")
squart = dizi13**2
print(dizi13)
print(squart)


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
print("Soru19")
dizi19 = np.random.randint(-50,51, size =(3,5))
print(dizi19)

pozitif_cift = dizi19[(dizi19 > 0) & (dizi19 %2==0)]
print(pozitif_cift)

Soru16
44
Soru17
[10 11 12 13 14 15 16 17 18 19 20]
[10 18 37]
Soru18
[10 11 12 13 14 15 16 17 18 19 20]
[100 121 144 169 196 225 256 289 324 361 400]
Soru19
[[-17  20  -2   5 -29]
 [-19  -9  16 -49  12]
 [-41  -8   9  30 -17]]
[20 16 12 30]
